### ISSUE TITLE
How to set base rem for different device sizes

### ISSUE THREAD

**Issue by CarliBotes** [jaredh159/tailwind-react-native-classnames#103]
I'm not able to find how one set the base rem for different device sizes in the documentation

E.g. for some larger devices I might want base rem of 17 and for smaller ones I might want rem 14, otherwise I want rem 15

Please help :)

**Comment by jaredh159** [comment]
Yeah, that's because there is no way to set a base rem, like in a web page (at least currently).  Instead, you would use the faux media queries, like `text-sm md:text-lg` etc.  If that sounds like a hassle, it's often significantly mitigated by the common best practice recommended by RN of making your own `<Text />` component wrapper, which encapsulates the styling for your app, and using that instead of the default one from RN.  In one of my apps, for instance, I have a `<Sans />` and `<Serif />` component, which take some basic props (like size), and under the hood I can use the media queries to adapt the sizes if I wanted.  This isolates that logic and complexity in one spot, and allows you to get relative font sizing based on device size, much like you would on the web with rems and a base font size.

Just wondering, are you possibly using RN for web?  I could see wanting base rem a lot more if I was in a web mindset.  This library does not aim to support RN web (at least not yet), so you might also find some other pain points if web is your target.

**Comment by ospfranco** [comment]
@jaredh159 are you sure this is correct? rem units are based on a specific size based on the root elem:

> rem
> rem values are relative to the root html element, not to the parent element. That is, If font-size of the root element is 16px then 1 rem = 16px for all elements. If font-size is not explicitly defined in root element then 1rem will be equal to the default font-size provided by the browser (usually 16px).

On tailwind for the web one can just set the base size on the root element, in one my projects I have:

```css
html {
  font-size: 15px
}
```

So then text utilities such as `text-sm` are based on 15px and not 16px, it would be great if twrnc could replicate this behavior.

**Comment by ospfranco** [comment]
nope, I'm using RN in mobiles and macOS, it's just a convenience, but I understand if this creates too much work. Thanks anyways!

**Comment by John-Colvin** [comment]
Font scaling (Dynamic Type in iOS land) means that the default font size will often be different from 16, no? If the whole point of rem is to be relative to the window font size, shouldn't it well... be relative to the window font size?
