### ISSUE TITLE
whats the difference between this and tailwind-rn

### ISSUE THREAD

**Issue by TalhaAbid** [jaredh159/tailwind-react-native-classnames#110]
Which should I use over another, what's the benefit?

**Comment by jaredh159** [comment]
`tailwind-rn` is a great library, if it meets your needs you should use it.

I made this library because I wanted a few more things, like:

- first-class typescript support
- platform prefixes: `android:mt-4 ios:mt-2`
- dark mode support: `bg-white dark:bg-black`
- media query support: `w-48 lg:w-64` (also, arbitrary: `min-w-[600px]:flex-wrap`)
- device orientation prefixes: `portrait:flex-col landscape:flex-row`
- `vw` and `vh` unit support: `h-screen`, `min-w-screen`, `w-[25vw]`, etc...
- `retina` device pixel density prefix: `w-4 retina:w-2`
- arbitrary, JIT-style classes: `mt-[31px] bg-[#eaeaea] text-red-200/75`, etc...
- tagged template literal synax

At least at the time of creating this library, `tailwind-rn` didn't have any of those features.  Not sure if it does now.

**Comment by TalhaAbid** [comment]
thank you for this, this is great and just what I needed. Perhaps add this to readme? Will make the decision easier for lots of people.

**Comment by TalhaAbid** [comment]
thank you!
