### ISSUE TITLE
Getting Error in React Native + Next JS app "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by ishields** [jaredh159/tailwind-react-native-classnames#162]
Hello I'm new to react native so bear with me. I started with this React Native + Next JS repo https://github.com/nandorojo/solito. The install of this package went fine however when adding a simple View to my screen like:

```
import { tw } from 'twrnc';
<View style={tw`bg-blue-100`}>
        <Text>Hello World</Text>
</View>
```   
I get an error `SyntaxError: Cannot use import statement outside a module`

I've actually noticed that if I add the above code on a running native or web the fast refresh actually refreshes correctly with the element styled.  However on a full refresh I get the error.  

Also I've tested with this package instead https://github.com/TVke/react-native-tailwindcss and it works fine but I'd prefer to use [tailwind-react-native-classnames](https://github.com/jaredh159/tailwind-react-native-classnames).  

Any advice on how I can fix the above error would be much appreciated.  Thanks!

**Comment by jaredh159** [comment]
I can't tell you exactly how to fix your issue, because it's not really a problem with this library, it has to do with how you've got your React Native web project setup, and I've never used RN web, nor does this library aim to support RN web (although some people use it successfully with RN web).

I can tell that that I believe that React Native ships un-transpiled es module code, and the build system in RN Native / Expo, etc, knows how to handle that. This library imports some dependencies from RN, and thus you're having a problem.  If I were you, I would google your error message _plus_ the words `React Native Web` or `React Native Web Nextjs`, and it's likely you'll find a github issue or stack overflow question to point you in the right direction. It's likely some sort of webpack, or babel or build tool configuration preset/setting that you're missing, is my hunch.  

Best of luck!

**Comment by ishields** [comment]
Thanks so much @jaredh159! Really appreciate your detailed suggestion. I'll continue looking.  Closing issue and will post any solution I find here after the fact in case it helps someone else.

**Comment by jaredh159** [comment]
sure thing @ishields  -- one other thought, you might try googling `metro-react-native-babel-preset` -- i think that has something to do with working around RN import stuff. might be a red herring, but might be useful.

**Comment by coxxanthony** [comment]
Fixed it with,

for next.config.js
`// @generated: @expo/next-adapter@4.0.9
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#withexpo
const { withExpo } = require('@expo/next-adapter');
const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')([
  'react-native-web',
  'react-native-reanimated',
  'react-native-web',
  'twrnc'
]);

const nextConfig = {
  reactStrictMode: true,
  webpack5: true,
  webpack: (config, options) => {
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      'react-native$': 'react-native-web',
    };
    config.resolve.extensions = [
      '.web.js',
      '.web.ts',
      '.web.tsx',
      ...config.resolve.extensions,
    ];
    return config;
  },
  images: {
    disableStaticImages: true,
  },
};

module.exports = withPlugins(
  [withTM, [withExpo, { projectRoot: __dirname }]],
  nextConfig
);`

And for babel.config.js
`// @generated: @expo/next-adapter@3.1.21
// Learn more: https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md#shared-steps

module.exports = { 
  presets: [
    '@expo/next-adapter/babel',
    [
      'babel-preset-expo',
      {
        web: { useTransformReactJSXExperimental: true },
      },
    ],
  ],
  plugins: [
    ['react-native-reanimated/plugin'],
    ['@babel/plugin-transform-flow-strip-types'],
    ['@babel/plugin-proposal-class-properties', { loose: true }], 
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    [
      '@babel/plugin-proposal-private-property-in-object',
      { loose: true }
    ],
  ],
};
`
