### ISSUE TITLE
`mx-auto` is not a valid Tailwind class name

### ISSUE THREAD

**Issue by wwsalmon** [jaredh159/tailwind-react-native-classnames#17]
`mx-auto` isn't working when I add it as a classname, but `marginLeft: "auto", marginRight: "auto"` work fine when directly styling. Any reason why this class (and `ml-auto`, `mr-auto`) aren't supported?

**Comment by jaredh159** [comment]
Hmmm... I don't think `margin: auto` works in RN.  Are you using React Native for _web_? It's not a goal of this project to fully support react native for web. Or am I wrong about it not working for native targets?

**Comment by maxdr** [comment]
Both `marginLeft: "auto"` and `marginRight: "auto"` should work in standard RN, [here](https://github.com/facebook/react-native/issues/350)'s a related issue. Neither `margin: auto` nor `marginHorizontal: auto` seem to be supported though.

**Comment by jaredh159** [comment]
@maxdr @wwsalmon OK, so I dug into this a bit more, and this should definitely be supported. I confirmed by playing with a snack that RN native doesn't support the `marginHorizontal: "auto"` or `marginVertical: "auto"` (though RN web does, which makes sense).  But this ends up not mattering, because the way this package works internally `mx-auto` and the like "compile" down to `{marginRight: "auto", marginLeft: "auto"}` anyway.

The next release (coming in a few minutes) will support all of the `m-auto` variants.  Thanks for the input. 👍

**Comment by jaredh159** [comment]
Released in `1.4.0`.
