### ISSUE TITLE
Certain classnames not generating styles appropriately.

### ISSUE THREAD

**Issue by acalvino4** [jaredh159/tailwind-react-native-classnames#179]
Some classnames are not generating styles appropriately:
```js
import tw from 'twrnc';
...
console.log(tw`w-[50vw]`);
// {}
console.log(tw`w-screen`);
// {}
console.log(tw`w-[13px]`);
// {width: 13}
console.log(tw`w-8`);
// {width: 32}
```
The last two examples are as expected. I included them to give a better idea of specifically what is and is not working for me.

**Comment by jaredh159** [comment]
this is likely caused by a failure to properly configure `tw` with device context, because in order to calculate things that have to do with the screen width, it needs device data. did you follow the steps in this section of the readme?

https://github.com/jaredh159/tailwind-react-native-classnames#enabling-device-context-prefixes

**Comment by acalvino4** [comment]
ahh makes sense. I did not realize that that applied to `vw` but I can see why it does. Thanks!
