### ISSUE TITLE
Inline style performance

### ISSUE THREAD

**Issue by JamesHemery** [jaredh159/tailwind-react-native-classnames#185]
Hi @jaredh159 ,

Just out of curiosity, did you benchmark the use of StyleSheet.create()? I think it could improve performance, but maybe you have already tried it?

Bye :)

**Comment by jaredh159** [comment]
no, i haven't. you're welcome to give it a shot if you're interested. 👍

**Comment by khagesh** [comment]
I was also interested in performance and found this repo https://github.com/efstathiosntonas/react-native-style-libraries-benchmark . It is interesting that this library, even though it parses styles at runtime, is much faster than NativeWind which uses babel plugins to transform classNames to styles object at compile time. I just cannot understand why that is the case. I guess I need to dive into NativeWind codebase and see what they are doing which makes them slow and why this library is fast.
Also, @jaredh159 does this library (twrnc) works for react native web as well?

**Comment by jaredh159** [comment]
@khagesh benchmarks are notoriously tricky to get right, you often end up measuring the wrong thing, or the signal is lost in noise of some sort or other. my intuition is that NativeWind would be faster as well, so I might look more deeply into the methodology of the benchmark.

that said, it's possible twrnc is really faster in some meaningful way, we strive to be very performant with heavy caching, including optimizing and caching whole groups of utilities.

no, this library is not designed for RN web. It's compatible, but there are many missing utilities for web, since we only aim for API coverage for the RN native style props, and supporting web would introduce many more utilities that don't exist in native (like css grid, for example)

**Comment by khagesh** [comment]
> @khagesh benchmarks are notoriously tricky to get right, you often end up measuring the wrong thing, or the signal is lost in noise of some sort or other. my intuition is that NativeWind would be faster as well, so I might look more deeply into the methodology of the benchmark.

So true. I looked into benchmark, and I found that a single style was used to render multiple views. This library has advantage that there is no extra cruft added on top of a view. While in NativeWind, they wrap native component with their own wrapper that takes longer to render. So styles is not the limiting factor for performance.

> no, this library is not designed for RN web. It's compatible, but there are many missing utilities for web, since we only aim for API coverage for the RN native style props, and supporting web would introduce many more utilities that don't exist in native (like css grid, for example)

Thank you for answering. And thank you for creating this library.

**Comment by lud** [comment]
Hello, 

Is it possible to do something like that?:  

```typescript
function MyComponent() {
  return <Text style={styles.someText}>Hello!</Text>
}

const styles = {
  someText: tw`px-3 font-400`
}

**Comment by jaredh159** [comment]
@lud should be possible. i'd still try to measure if i was actually facing a perf issue from the style gen, but if this floats your boat, go for it 👍

**Comment by lud** [comment]
Thanks @jaredh159 :)
