### ISSUE TITLE
How to use custom font ?

### ISSUE THREAD

**Issue by shellord** [jaredh159/tailwind-react-native-classnames#191]
How do I use a custom font with twrnc ?

**Comment by husnuljahneer** [comment]
I was also looking for this! Someone be quick with this, please.

**Comment by shellord** [comment]
I added font like this. but I have to add font-sans class to every text to make it show.
Is there a way I can change all font family ? 

```
module.exports = {
  theme: {
    fontFamily: {
      sans: ['Montserrat-Regular'],
    },
}
```

**Comment by jaredh159** [comment]
in RN, there is not really a concept of the css _cascade_, so thing don't work like you would intuitively expect, coming from a web background (which I was). therefore, yes, you would have to supply the font utility on every instance of using the Text component.

one thing that is fairly common (and what I tend to do) is create my own `<Text />` component wrapper (in one project I have one called `<Sans />` and one called `<Serif />`, and those apply my font family (and other styles), and I tend to import and use those instead of using RN's `Text` component directly.

**Comment by mcnaveen** [comment]
Is it the same now?

Here is what I did so far.

1. Create a `tailwind.config.js` file with the below content.
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    fontFamily: {
      cal: ['Cal Sans', 'sans-serif'],
    },
  },
};
```
2. Placed the font in `./assets/fonts` directory

Confused how to proceed further.

**Comment by shellord** [comment]
> Is it the same now?
> 
> Here is what I did so far.
> 
> 1. Create a `tailwind.config.js` file with the below content.
> 
> ```
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   theme: {
>     fontFamily: {
>       cal: ['Cal Sans', 'sans-serif'],
>     },
>   },
> };
> ```
> 
> 2. Placed the font in `./assets/fonts` directory
> 
> Confused about how to proceed further? Because I'm getting a below warning.
> 
> ```
>  WARN  `cal` unknown or invalid utility 
> ```

You are using `font-cal` right ?

**Comment by mcnaveen** [comment]
Hi, @shellord Yes. I'm using font-cal.

**Comment by doong-jo** [comment]
@mcnaveen 

## tailwind.config.js

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {},
    fontFamily: {
      pyeongchang: ['PyeongChang', 'sans-serif'],
    },
  },
  plugins: [],
};
```

## Create tw you own

```ts
import { create } from 'twrnc';

const tailwindConfig = require('../../../tailwind.config');

export const tw = create(tailwindConfig);
```


## Use custom font

```ts
export function AppTitle() {
  return (
    <Text style={tw`font-pyeongchang text-[65px] font-bold`}>
      Hello World
    </Text>
  );
}
```
