### ISSUE TITLE
space–x–*  and gap–* attributes does not exist.

### ISSUE THREAD

**Issue by AyoCodess** [jaredh159/tailwind-react-native-classnames#200]
Am i doing something wrong here?  ``space–x–$``does not exist 
<img width="389" alt="Screenshot 2022-11-02 at 23 51 48" src="https://user-images.githubusercontent.com/72066389/199617598-6037b9a7-2bb9-451e-8904-5d5dec3d56cb.png">
<img width="793" alt="Screenshot 2022-11-02 at 23 51 41" src="https://user-images.githubusercontent.com/72066389/199617599-1add2c82-43c1-4583-bb50-1dacc20e34af.png">

**Comment by jaredh159** [comment]
those utilities aren't representable as Rn native styles. this library only supports a subset of tailwind, the stuff that works in Rn native (not Rn web). that includes stuff like _all_ of css grid, which is not possible in Rn.

**Comment by Neocor89** [comment]
Hello, 
I have the same problem, is there an alternative to correct it ?

**Comment by AyoCodess** [comment]
> those utilities aren't representable as Rn native styles. this library only supports a subset of tailwind, the stuff that works in Rn native (not Rn web). that includes stuff like _all_ of css grid, which is not possible in Rn.

Thanks for getting back to me. These styles work with NativeWind. Is not away to add them? 

Great library by the way. The platform specific styles are great.

**Comment by jaredh159** [comment]
@Neocor89 there's really no way to _correct_ it, because RN doesn't support that form of styling. So even if we were to add support for these utilities, they would have _no effect whatsoever_ unless you were using RN Web.  This library is focused on RN _native_, not RN web.

@AyoCodess along the same lines, if it works in NativeWind, that's great, you're welcome to use that library of course, just realize it _will only work in RN Web_.
