### ISSUE TITLE
How to set hairlineWidth?

### ISSUE THREAD

**Issue by yqz0203** [jaredh159/tailwind-react-native-classnames#201]
Somewhere explained this?

**Comment by rborn** [comment]
You could probably add it in the theme?

**Comment by jaredh159** [comment]
i hadn't even ever heard of that property, had to look it up.  there is no utility in this library for it, because this library only covers utilities that exist in tailwindcss and also make sense for react-native. so, in this case, it makes sense for react-native, but i don't think exists in tailwindcss.

you could define a custom utility, or just pass it through as a style prop, as shown in the docs.
