### ISSUE TITLE
Prettier Plugin Tailwindcss

### ISSUE THREAD

**Issue by sameretto** [jaredh159/tailwind-react-native-classnames#213]
Hi is it possible to make this package work with the official prettier plugin they have?

source: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

**Comment by jaredh159** [comment]
i'm not sure. i'm guessing it probably won't work out of the box, since the prettier plugin probably operates on a concept of `className` string attributes, instead of the RN/twrnc `style` props.  you might try reading (and possibly posting) in this thread for some more help/context:

https://github.com/jaredh159/tailwind-react-native-classnames/discussions/124
