### ISSUE TITLE
Support adding gradient to background

### ISSUE THREAD

**Issue by karwan-ali** [jaredh159/tailwind-react-native-classnames#219]
Hello,

I was wondering if it is possible to implement gradient to background like in normal tailwindcss?

Example:
bg-gradient-to-b

My React Native app can't find gradient styles. See attached images.
<img width="411" alt="Screenshot 2023-02-12 at 21 20 19" src="https://user-images.githubusercontent.com/38838635/218335034-779cbc92-183c-4461-9616-4ae4490d4e9a.png">

I also get error when adding "from-black to-white":
<img width="400" alt="Screenshot 2023-02-12 at 21 21 04" src="https://user-images.githubusercontent.com/38838635/218335067-ad154b2e-dbcb-4895-94f3-ad98ff778a9f.png">

**Comment by jaredh159** [comment]
We don't support gradients at all. That's because this library is only aiming to cover tailwindcss utilities that map directly to core style props in RN native. Gradients are not supported directly in RN (native).

I'm guessing you might be using RN web? If so, check out the discussion here: https://github.com/jaredh159/tailwind-react-native-classnames/discussions/125

also: 

https://github.com/jaredh159/tailwind-react-native-classnames/issues/156

**Comment by karwan-ali** [comment]
Oh sorry, I was going to write another comment as I found a library that took care of this. I was not aware that gradient was not supported in RN. Thank you for the fast reply!

If other people are interested in what library I used for implementing gradient:
expo-linear-gradient
