### ISSUE TITLE
Auto-import not working when I type "tw", only "tailwind"

### ISSUE THREAD

**Issue by ElektrikSpark** [jaredh159/tailwind-react-native-classnames#23]
I might be missing something here, but I am only able to auto-import tailwind-react-native-classnames when I start to type out `tailwind`, and the import is `import tailwind from "tailwind-react-native-classnames";`.  How can I set this up to auto-import when I type `tw`, and give me `import tw from "tailwind-react-native-classnames";`?  Is this not set up as the default by this library?

**Comment by jaredh159** [comment]
The [main entry file](https://github.com/jaredh159/tailwind-react-native-classnames/blob/master/src/index.ts) for the library exports one _default export_ and one _named export_. 

As to how you're getting auto-imports, that's an **editor thing.**  If you're using vscode, I'm guessing it's supplying `tailwind` and not `tw` because the name of the function exported as the default is `tailwind`, so maybe it uses that as a guess.  But, because it's a default export, you can name it whatever you want, which is why editors have to guess, I'd imagine.

The only think I think I could do to influence this would be to rename the variable exported as default, but I'm not sure everyone would have your preference of calling the function `tw`.  Also, I think the most common use case for this library is to set up a _configured_ version of the function using your own tailwind config, as described in the readme--which means most people end up importing `tw` from their _own_ file, and not from the package directly.

**Comment by ElektrikSpark** [comment]
Thank you for the response.  I have attempted to follow the documentation on customization to get this to work, but I ran into an issue with `npx trnc-create-styles`.  I have posted on that issue with more details.  

Just a thought, and please let me know your own thoughts, but I feel that if the documentation uses `tw` as the standard naming convention throughout, allowing VSCode to pick up on that and auto-import it correctly out-of-the-box seems like the right call.  I think your guess is correct, and if you changed the name of the function being exported from `tailwind` to `tw` it would work by default, but maybe there is some other trick that is used, I am not sure.  I agree that some people may prefer `tailwind`, but I feel that aligning the name with the documentation by default is the most important thing.

**Comment by jaredh159** [comment]
@ElektrikSpark `1.4.2` changes the default export name.  Let me know if that seems to improve the flow for you.

**Comment by ElektrikSpark** [comment]
That did it, thanks a lot.  Now when I just want to quickly prototype something I just type `style={tw}` and I get the auto-import, no additional boilerplate, just have to install the library.  I think this is one of those little details that will go a long way.
