### ISSUE TITLE
Advice for class utility

### ISSUE THREAD

**Issue by electroheadfx** [jaredh159/tailwind-react-native-classnames#27]
I'd would like add a class utility globally, Iam not sure if its the right location in this file : https://tailwindcss.com/docs/adding-new-utilities
is not customizable from root  ?

**Comment by jaredh159** [comment]
It should theoretically work as long as tailwind and postcss can find your *.css file.

Just a heads-up though, at some point when v2 of this library is released (which functions more like the new JIT feature in tailwind), I don't think this approach will work for the new version, because it won't parse actual CSS ahead of time.

**Comment by electroheadfx** [comment]
thanks for the advice, I will avoid that. Actually I add new data to theme from tailwind.config.js and I make my component re-usable with props and tw.style
