### ISSUE TITLE
What is the minimum version of support for reactnative? 

### ISSUE THREAD

**Issue by faimin** [jaredh159/tailwind-react-native-classnames#308]
```json
  "dependencies": {
    "tailwindcss": ">=2.0.0"
  },
  "peerDependencies": {
    "react-native": ">=0.63.0"
  },
  ```
  
the minimum version of support for reactnative is `0.63.0` ?

**Comment by jaredh159** [comment]
that's what's listed now. i think because that was the version of RN when i first created the project.

are you trying to build for RN older than `0.63.0`? my guess is it should work fine, although some of the utilities may not work if they are leveraging newer style props. i'd be open to moving the min version back if you can show that it work fine with older versions

**Comment by faimin** [comment]
yes, the version we are using is `0.62.2`. I will try it later, thanks for your answer.

**Comment by faimin** [comment]
awesome, it works in my project that `ReactNative` version is `0.62.2`.

**Comment by jaredh159** [comment]
thanks for reporting back. tagged `4.5.1` with the new minimum version
