### ISSUE TITLE
Can't implement DaisyUI

### ISSUE THREAD

**Issue by onlineworld69** [jaredh159/tailwind-react-native-classnames#55]
Hello team. 

First of all, thank you for creating v2. I love it. Keep it up the good work.

I want to add Daisyui and I couldn't make it work.  Plz advise! Tks.

// lib/tailwind.js
import { create } from 'twrnc';

const tw = create(require(`../../tailwind.config.js`)); // <- your path may differ
export default tw;

//tailwind.config.js
const { plugin } = require("twrnc");

module.exports = {
  plugins: [plugin(() => require("daisyui"))],
};

//App.tsx

import tw from "./lib/tailwind";

<TouchableOpacity
   style={tw` btn-primary btn`}
    onPress={() => console.log("pressed")}>
      <Text>Daisy UI Button</Text>
</TouchableOpacity>

**Comment by jaredh159** [comment]
I can't say exactly why this isn't working, but I would definitely discourage you from trying to make DaisyUI work with `twrnc`. The reason is that DaisyUI is a framework for tailwind on the **web**, and `twrnc` _only supports the subset of tailwindcss that works on React Native **non-web**._  So, even if you could get the plugin to work, the components would only render correctly if they happened to _only use css properties supported by RN native,_ which is very unlikely.
